# CONFIGURACIÓN DEL SERVIDOR
spring.application.name=${SPRING_APPLICATION_NAME:SistemaAvanzadoFinanciero}
server.port=${SERVER_PORT:4000}
spring.cors.allowed.origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

# BASE DE DATOS
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

# CONFIGURACIÓN JPA / HIBERNATE
# Estas variables es mejor dejarlas estáticas ya que rara vez cambian entre entornos
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.web.pageable.one-indexed-parameters=true

# SEGURIDAD JWT
security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY}
security.jwt.expiration-time=${SECURITY_JWT_EXPIRATION_TIME}